# Generated by Django 5.1.4 on 2025-01-21 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('confirm_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsersStudy',
            fields=[
                ('study_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_name', models.CharField(max_length=255)),
                ('study_description', models.TextField()),
                ('study_phase', models.CharField(choices=[('Phase I', 'Phase I'), ('Phase II', 'Phase II'), ('Phase III', 'Phase III'), ('Phase IV', 'Phase IV')], max_length=255)),
                ('sponser_name', models.CharField(blank=True, max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyapp.register')),
            ],
        ),
    ]
